Updates code sample
vala-lang/vala-www pull request #127
Opened 2022-07-01 15:30 UTC by rakshit087

Fixes #117 
Let me know if someone has a better idea for example. I was thinking of working on a counter application which shows the number of times a button is clicked but I don't have the idea of the best practices to write Vala.

2022-07-01 15:40 UTC, nahuelwexd requested changes

2022-07-01 15:40 UTC, nahuelwexd commented on assets/code-sample.md
> +    win.present();
I prefer to keep the spacing, it makes it more readable.

```suggestion
    var win = new Gtk.ApplicationWindow(app);

    var btn = new Gtk.Button.with_label("Hello World");
    btn.click.connect(win.close);

    win.child = btn;
    win.present();
```

2022-07-04 18:36 UTC, colinkiama requested changes

2022-07-04 19:24 UTC, colinkiama approved these changes

2022-07-04 19:26 UTC, merged

2022-07-04 19:26 UTC, colinkiama commented
Thanks!