adjusted the line height
vala-lang/vala-www pull request #202
Opened 2023-07-26 08:06 UTC by anubhav1206

2023-07-28 08:04 UTC, colinkiama requested changes
Sorry, my fault, I should have been more clear.

The changes you've made to these files should be reverted. Only `sass/css/_base.scss` needs to be modified.

Modify the `line-height` set on `body`.

`1` is a bit too low for `line-height`. Even Google Chrome's default `line-height` is `1.2`. Maybe try `1.3`?

2023-07-28 09:05 UTC, anubhav1206 commented
sure will make the changes

> Sorry, my fault, I should have been more clear.
> 
> The changes you've made to these files should be reverted. Only `sass/css/_base.scss` needs to be modified.
> 
> Modify the `line-height` set on `body`.
> 
> `1` is a bit too low for `line-height`. Even Google Chrome's default `line-height` is `1.2`. Maybe try `1.3`?

2023-07-28 09:08 UTC, anubhav1206 commented
done, kindly check

2023-07-28 17:42 UTC, colinkiama commented on sass/css/_reset.scss
> +  line-height: 1; /* 1 */
```suggestion
  line-height: 1.15; /* 1 */
```

2023-07-28 17:43 UTC, colinkiama commented on sass/css/index.scss
> +  line-height: 1;
```suggestion
```

2023-07-28 17:45 UTC, colinkiama commented on sass/css/index.scss
> +}
```suggestion
```

2023-07-28 17:47 UTC, colinkiama requested changes
Almost there...

After making these final changes, your contribution will be ready to merge 😄️.

2023-07-28 17:47 UTC, colinkiama commented on sass/css/_reset.scss
> +  line-height: 1; /* 1 */
Change this back

2023-07-28 17:47 UTC, colinkiama commented on sass/css/index.scss
> +}
Remove this change

2023-07-28 17:54 UTC, anubhav1206 commented
> Almost there...
> 
> After making these final changes, your contribution will be ready to merge 😄️.

done, kindly check

2023-07-29 10:20 UTC, colinkiama commented on sass/css/index.scss
> +
```suggestion
```

2023-07-29 10:21 UTC, colinkiama approved these changes
Perfect! Thank you!

2023-07-29 10:22 UTC, merged