Modernize code sample
vala-lang/vala-www pull request #203
Opened 2023-08-24 09:51 UTC by realmazharhussain

2023-08-24 10:28 UTC, lw64 requested changes
Thank you a lot! :)

2023-08-24 10:28 UTC, lw64 commented on assets/code-sample.md
> +    application_id = "com.example.App";
Please use the `Object()` syntax here

2023-08-24 10:28 UTC, lw64 commented on assets/code-sample.md
>      var btn = new Gtk.Button.with_label("Hello World");
And leave a space before `(`'s

2023-08-24 10:53 UTC, realmazharhussain commented on assets/code-sample.md
> +    application_id = "com.example.App";
Done.

2023-08-24 10:53 UTC, realmazharhussain commented on assets/code-sample.md
>      var btn = new Gtk.Button.with_label("Hello World");
Done

2023-08-25 02:11 UTC, realmazharhussain commented
DEFAULT_FLAGS was introduced in a somewhat new version of GLib and FLAGS_NONE was deprecated in favor of it. That is why I used DEFAULT_FLAGS.

You are probably using a non-rolling distro that ships a somewhat older version of GLib where DEFAULT_FLAGS does not exist yet.

2023-08-25 04:36 UTC, colinkiama commented on assets/code-sample.md
>  // Compile command (requires gtk4 package to be installed):
```suggestion
// Compile command (requires "glib-2.0" package on version 2.74 or higher and "gtk4" package to be installed):
```

2023-08-25 05:09 UTC, colinkiama commented
That should do it. Thanks!

2023-08-25 05:09 UTC, merged